[platformio]
src_dir = .
include_dir = .

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
src_filter = +<main.c> +<display.c> +<input.c> +<audio.c> +<eeprom.c> +<tetris_game.c> +<tetris_render.c> +<flappy_game.c> +<flappy_render.c>